# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1liLABompchy4FMoKfqilbXI8OR9HcCBE
"""



import numpy as np
import pickle
import streamlit as st
import pandas as pd

# Загрузка предобученной модели и трансформера для нормализации
try:
    loaded_model = pickle.load(open('model_regressor.sav', 'rb'))
    min_max_scaler = pickle.load(open('transformer.sav', 'rb'))
except FileNotFoundError as e:
    st.error(f"Ошибка: Не найден файл модели или трансформера. Проверьте наличие файлов в папке. ({e})")

def predict_matrix_ratio(input_data):
    """
    Функция принимает список физических параметров,
    нормализует их, делает предсказание и возвращает денормализованный результат.
    """
    # Точный список колонок в том порядке, в котором обучалась модель
    feature_names = [
        'Соотношение матрица-наполнитель', 'Плотность, кг/м3', 'модуль упругости, ГПа',
        'Количество отвердителя, м.%', 'Содержание эпоксидных групп,%_2', 'Температура вспышки, С_2',
        'Поверхностная плотность, г/м2', 'Модуль упругости при растяжении, ГПа', 'Прочность при растяжении, МПа',
        'Потребление смолы, г/м2', 'Угол нашивки, град', 'Шаг нашивки', 'Плотность нашивки'
    ]

    # Превращаем плоский список в двумерную матрицу (1 строка, 13 столбцов)
    input_array = np.array(input_data).reshape(1, -1)

    # Создаем DataFrame для корректной работы scaler'а (ему нужны имена колонок)
    df = pd.DataFrame(input_array, columns=feature_names)

    # Нормализуем данные (переводим в диапазон 0-1)
    df_norm = pd.DataFrame(min_max_scaler.transform(df), columns=feature_names)

    # Убираем целевой параметр из признаков перед отправкой в модель
    features_for_prediction = df_norm.drop('Соотношение матрица-наполнитель', axis=1)

    # Делаем предсказание
    y_pred = loaded_model.predict(features_for_prediction)

    # Записываем предсказанное значение обратно в нормализованную таблицу
    df_norm['Соотношение матрица-наполнитель'] = y_pred

    # Проводим обратное преобразование, чтобы вернуть данные к реальным физическим величинам
    df_denorm = pd.DataFrame(min_max_scaler.inverse_transform(df_norm), columns=feature_names)

    # Возвращаем итоговое предсказанное соотношение
    return df_denorm['Соотношение матрица-наполнитель'][0]

def main():
    st.set_page_config(page_title="Composite Predictor", layout="centered")
    st.title('Прогноз соотношения матрица-наполнитель')
    st.write("Введите физико-механические характеристики композитного материала:")

    # Целевой параметр инициализируем нулем (заглушка для функции)
    matrix_placeholder = 0.0

    # Создаем числовые поля ввода с безопасными значениями по умолчанию
    density = st.number_input('Плотность, кг/м3', min_value=0.0, value=1500.0, step=10.0)
    elasticity = st.number_input('Модуль упругости, ГПа', min_value=0.0, value=4.5, step=0.1)
    hardener = st.number_input('Количество отвердителя, м.%', min_value=0.0, value=100.0, step=1.0)
    epoxy = st.number_input('Содержание эпоксидных групп,%_2', min_value=0.0, value=20.0, step=0.5)
    temperature = st.number_input('Температура вспышки, С_2', min_value=0.0, value=250.0, step=5.0)
    surface_density = st.number_input('Поверхностная плотность, г/м2', min_value=0.0, value=150.0, step=5.0)
    elastic_modulus = st.number_input('Модуль упругости при растяжении, ГПа', min_value=0.0, value=70.0, step=1.0)
    toughness = st.number_input('Прочность при растяжении, МПа', min_value=0.0, value=1000.0, step=10.0)
    resin_consumption = st.number_input('Потребление смолы, г/м2', min_value=0.0, value=200.0, step=5.0)
    patch_angle = st.number_input('Угол нашивки, град', min_value=0.0, max_value=360.0, value=0.0, step=5.0)
    patch_pitch = st.number_input('Шаг нашивки', min_value=0.0, value=10.0, step=0.5)
    patch_density = st.number_input('Плотность нашивки', min_value=0.0, value=50.0, step=1.0)

    # Логика обработки нажатия кнопки
    if st.button('Рассчитать', type='primary'):
        # Собираем все признаки в единый список
        features_list = [
            matrix_placeholder, density, elasticity, hardener, epoxy,
            temperature, surface_density, elastic_modulus, toughness,
            resin_consumption, patch_angle, patch_pitch, patch_density
        ]

        try:
            prediction = predict_matrix_ratio(features_list)
            st.success(f'**Рекомендуемое соотношение матрица-наполнитель:** {prediction:.4f}')
        except Exception as e:
            st.error(f"Произошла ошибка во время расчета: {e}")

if __name__ == '__main__':
    main()